Hounted123
Autoscript Debian 7 SSH, Squid, OpenVPN, BadVPN

diff --git a/Hounted123 b/Hounted123
--- a/Hounted123
+++ b/Hounted123
@@ -1,23 +1,37 @@
 #!/bin/bash
 #
-# Original script by fornesia, rzengineer and fawzya
-# Mod by Bustami Arifin
-# Translation by _Dreyannz_
-#Remodified by Hounted123
+# Original script by fornesia, rzengineer and fawzya 
+# Mod by Hounted for Adding OCS Panel
+# 
 # ==================================================
 
-# Initializing Var
+MYIP=$(wget -qO- ipv4.icanhazip.com);
+: '
+# check registered ip
+wget -q -O daftarip http://188.166.215.119:85/ocs/ip.txt
+if ! grep -w -q $MYIP daftarip; then
+	echo "Sorry, only registered IPs can use this script!"
+	if [[ $vps = "vps" ]]; then
+		echo "Powered by Hounted"
+	else
+		echo "Powered by Hounted"
+	fi
+	rm -f /root/daftarip
+	exit
+fi
+'
+# initialisasi var
 export DEBIAN_FRONTEND=noninteractive
 OS=`uname -m`;
 MYIP=$(wget -qO- ipv4.icanhazip.com);
 MYIP2="s/xxxxxxxxx/$MYIP/g";
 
-# Details of Hounted123
-country=PH
+#detail nama perusahaan
+country=ID
 state=Manila
 locality=Manila
 organization=PHCorner
-organizationalunit=PHCorner
+organizationalunit=PHC
 commonname=PHC
 email=Hafabajtc@yahoo.com
 
@@ -39,7 +53,7 @@ sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
 service ssh restart
 
 # set repo
-wget -O /etc/apt/sources.list "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/sources.list.debian7"
+wget -O /etc/apt/sources.list "https://raw.githubusercontent.com/Hounted123/Hounted1/master/sources.list.debian7"
 wget "http://www.dotdeb.org/dotdeb.gpg"
 cat dotdeb.gpg | apt-key add -;rm dotdeb.gpg
 sh -c 'echo "deb http://download.webmin.com/download/repository sarge contrib" > /etc/apt/sources.list.d/webmin.list'
@@ -62,7 +76,7 @@ echo -e "\e[94m         _|    _|  _|    _|  _|    _|  _|      _|_|     _|      _
 echo -e "\e[94m         _|    _|  _|_|_|_|  _|_|_|_|  _|        _|     _|      _|_|_|_|  _|_|_|   "
 echo -e "\e[94m.  ---------------------------------------------------------------      "
 echo 'echo -e "\e[94m   #########  ########## #########      ###       "' >> .bashrc
-echo 'echo -e "\e[94m         VPSAutoScript by PHCarl          "' >> .bashrc
+echo 'echo -e "\e[94m         VPSAutoScript by Hounted          "' >> .bashrc
 echo 'echo -e "\e[0m"'                                                    >> .bashrc
 echo 'echo -e "\e[94m##################################################"' >> .bashrc
 echo 'echo -e "\e[94m#   Commands           Description               #"' >> .bashrc
@@ -84,43 +98,42 @@ echo 'echo -e "\e[94m#                                                #"' >> .ba
 echo 'echo -e "\e[94m##################################################"' >> .bashrc
 echo 'echo -e "\e[0m                                                   "' >> .bashrc
 
+
 # install webserver
 cd
 rm /etc/nginx/sites-enabled/default
 rm /etc/nginx/sites-available/default
-wget -O /etc/nginx/nginx.conf "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/nginx.conf"
+wget -O /etc/nginx/nginx.conf "https://raw.githubusercontent.com/Hounted123/Hounted1/master/nginx.conf"
 mkdir -p /home/vps/public_html
-echo "<pre>Setup by Bustami Arifin</pre>" > /home/vps/public_html/index.html
-echo "<pre>Translation by _Dreyannz_</pre>" > /home/vps/public_html/index.html
-echo "<pre>Remodified by PHCarl </pre>"> /home/vps/public_html/index.html
-wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/vps.conf"
+echo "<pre>Setup by Clrkz</pre>" > /home/vps/public_html/index.html
+wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/Hounted123/Hounted1/master/vps.conf"
 service nginx restart
 
 # install openvpn
-wget -O /etc/openvpn/openvpn.tar "https://github.com/PHCarl10/Deb7AutoScriptVPS/raw/master/openvpn-debian.tar"
+wget -O /etc/openvpn/openvpn.tar "https://github.com/Hounted123/Hounted1/raw/master/openvpn-debian.tar"
 cd /etc/openvpn/
 tar xf openvpn.tar
-wget -O /etc/openvpn/1194.conf "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/1194.conf"
+wget -O /etc/openvpn/1194.conf "https://raw.githubusercontent.com/Hounted123/Hounted1/master/1194.conf"
 service openvpn restart
 sysctl -w net.ipv4.ip_forward=1
 sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf
 iptables -t nat -I POSTROUTING -s 192.168.100.0/24 -o eth0 -j MASQUERADE
 iptables-save > /etc/iptables_yg_baru_dibikin.conf
-wget -O /etc/network/if-up.d/iptables "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/iptables"
+wget -O /etc/network/if-up.d/iptables "https://raw.githubusercontent.com/Hounted123/Hounted1/master/iptables"
 chmod +x /etc/network/if-up.d/iptables
 service openvpn restart
 
-# openvpn configuration
+# konfigurasi openvpn
 cd /etc/openvpn/
-wget -O /etc/openvpn/client.ovpn "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/client-1194.conf"
+wget -O /etc/openvpn/client.ovpn "https://raw.githubusercontent.com/Hounted123/Hounted1/master/client-1194.conf"
 sed -i $MYIP2 /etc/openvpn/client.ovpn;
 cp client.ovpn /home/vps/public_html/
 
 # install badvpn
 cd
-wget -O /usr/bin/badvpn-udpgw "https://github.com/PHCarl10/Deb7AutoScriptVPS/raw/master/badvpn-udpgw"
+wget -O /usr/bin/badvpn-udpgw "https://github.com/Hounted123/Hounted1/raw/master/badvpn-udpgw"
 if [ "$OS" == "x86_64" ]; then
-  wget -O /usr/bin/badvpn-udpgw "https://github.com/PHCarl10/Deb7AutoScriptVPS/raw/master/badvpn-udpgw64"
+  wget -O /usr/bin/badvpn-udpgw "https://github.com/Hounted123/Hounted1/raw/master/badvpn-udpgw64"
 fi
 sed -i '$ i\screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300' /etc/rc.local
 chmod +x /usr/bin/badvpn-udpgw
@@ -129,14 +142,14 @@ screen -AmdS badvpn badvpn-udpgw --listen-addr 127.0.0.1:7300
 # setting port ssh
 cd
 sed -i 's/Port 22/Port 22/g' /etc/ssh/sshd_config
-sed -i '/Port 22/a Port 143' /etc/ssh/sshd_config
+sed -i '/Port 22/a Port 444' /etc/ssh/sshd_config
 service ssh restart
 
 # install dropbear
 apt-get -y install dropbear
 sed -i 's/NO_START=1/NO_START=0/g' /etc/default/dropbear
-sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=443/g' /etc/default/dropbear
-sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 80"/g' /etc/default/dropbear
+sed -i 's/DROPBEAR_PORT=22/DROPBEAR_PORT=3128/g' /etc/default/dropbear
+sed -i 's/DROPBEAR_EXTRA_ARGS=/DROPBEAR_EXTRA_ARGS="-p 143"/g' /etc/default/dropbear
 echo "/bin/false" >> /etc/shells
 echo "/usr/sbin/nologin" >> /etc/shells
 service ssh restart
@@ -145,7 +158,7 @@ service dropbear restart
 # install squid3
 cd
 apt-get -y install squid3
-wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/squid3.conf"
+wget -O /etc/squid3/squid.conf "https://raw.githubusercontent.com/Hounted123/Hounted1/master/squid3.conf"
 sed -i $MYIP2 /etc/squid3/squid.conf;
 service squid3 restart
 
@@ -156,29 +169,49 @@ sed -i 's/ssl=1/ssl=0/g' /etc/webmin/miniserv.conf
 service webmin restart
 
 # install stunnel
-apt-get -y install stunnel4
-wget -O /etc/stunnel/stunnel.pem "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/stunnel.pem"
-wget -O /etc/stunnel/stunnel.conf "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/stunnel.conf"
-sed -i $MYIP2 /etc/stunnel/stunnel.conf
-sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
-service stunnel4 restart
+apt-get install stunnel4 -y
+cat > /etc/stunnel/stunnel.conf <<-END
+cert = /etc/stunnel/stunnel.pem
+client = no
+socket = a:SO_REUSEADDR=1
+socket = l:TCP_NODELAY=1
+socket = r:TCP_NODELAY=1
 
-# install fail2ban
-apt-get -y install fail2ban;
-service fail2ban restart
+
+[dropbear]
+accept = 443
+connect = 127.0.0.1:3128
+
+END
+
+#membuat sertifikat
+openssl genrsa -out key.pem 2048
+openssl req -new -x509 -key key.pem -out cert.pem -days 1095 \
+-subj "/C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"
+cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
+
+#konfigurasi stunnel
+sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
+/etc/init.d/stunnel4 restart
+
+# teks berwarna
+apt-get -y install ruby
+gem install lolcat
+
+# install fail2banapt-get -y install fail2ban;
+service fail2ban restart 
 
 # install ddos deflate
 cd
 apt-get -y install dnsutils dsniff
-wget https://github.com/PHCarl10/Deb7AutoScriptVPS/raw/master/ddos-deflate-master.zip
+wget https://github.com/Hounted123/Hounted1/raw/master/ddos-deflate-master.zip
 unzip ddos-deflate-master.zip
 cd ddos-deflate-master
 ./install.sh
-rm -rf /root/ddos-deflate-master.zip
+rm -rf /root/ddos-deflate-master.zip 
 
-# banner
-rm /etc/issue.net
-wget -O /etc/issue.net "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/issue.net"
+# bannerrm /etc/issue.net
+wget -O /etc/issue.net "https://raw.githubusercontent.com/Hounted123/Hounted1/master/issue.net"
 sed -i 's@#Banner@Banner@g' /etc/ssh/sshd_config
 sed -i 's@DROPBEAR_BANNER=""@DROPBEAR_BANNER="/etc/issue.net"@g' /etc/default/dropbear
 service ssh restart
@@ -188,45 +221,27 @@ service dropbear restart
 cd
 apt-get -y --force-yes -f install libxml-parser-perl
 
-#block torrent
-iptables -A OUTPUT -p tcp --dport 6881:6889 -j DROP
-iptables -A OUTPUT -p udp --dport 1024:65534 -j DROP
-iptables -A FORWARD -m string --string "get_peers" --algo bm -j DROP
-iptables -A FORWARD -m string --string "announce_peer" --algo bm -j DROP
-iptables -A FORWARD -m string --string "find_node" --algo bm -j DROP
-iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j DROP
-iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" -j DROP
-iptables -A FORWARD -m string --algo bm --string "peer_id=" -j DROP
-iptables -A FORWARD -m string --algo bm --string ".torrent" -j DROP
-iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" -j DROP
-iptables -A FORWARD -m string --algo bm --string "torrent" -j DROP
-iptables -A FORWARD -m string --algo bm --string "announce" -j DROP
-iptables -A FORWARD -m string --algo bm --string "info_hash" -j DROP
-
 # download script
 cd /usr/bin
-wget -O menu "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/menu.sh"
-wget -O add "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/usernew.sh"
-wget -O trial "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/trial.sh"
-wget -O remove "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/hapus.sh"
-wget -O check "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/user-login.sh"
-wget -O member "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/user-list.sh"
-wget -O banner "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/servermessage.sh"
-wget -O restart "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/resvis.sh"
-wget -O speedtest "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/speedtest_cli.py"
-wget -O info "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/info.sh"
-wget -O about "https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/about.sh"
-
+wget -O menu "https://raw.githubusercontent.com/Hounted123/Hounted1/master/menu.sh"
+wget -O usernew "https://raw.githubusercontent.com/Hounted123/Hounted1/master/usernew.sh"
+wget -O trial "https://raw.githubusercontent.com/Hounted123/Hounted1/master/trial.sh"
+wget -O delete "https://raw.githubusercontent.com/Hounted123/Hounted1/master/hapus.sh"
+wget -O check "https://raw.githubusercontent.com/Hounted123/Hounted1/master/user-login.sh"
+wget -O member "https://raw.githubusercontent.com/Hounted123/Hounted1/master/user-list.sh"
+wget -O restart "https://raw.githubusercontent.com/Hounted123/Hounted1/master/resvis.sh"
+wget -O speedtest "https://raw.githubusercontent.com/Hounted123/Hounted1/master/speedtest_cli.py"
+wget -O info "https://raw.githubusercontent.com/Hounted123/Hounted1/master/info.sh"
+wget -O about "https://raw.githubusercontent.com/Hounted123/Hounted1/master/about.sh"
 
 echo "0 0 * * * root /sbin/reboot" > /etc/cron.d/reboot
 
 chmod +x menu
-chmod +x add
+chmod +x usernew
 chmod +x trial
-chmod +x remove
+chmod +x delete
 chmod +x check
 chmod +x member
-chmod +x banner
 chmod +x restart
 chmod +x speedtest
 chmod +x info
@@ -245,45 +260,59 @@ service webmin restart
 rm -rf ~/.bash_history && history -c
 echo "unset HISTFILE" >> /etc/profile
 
-# install Screenfetch
-apt-get -y install lsb-release scrot
-wget -O screenfetch 'https://raw.githubusercontent.com/PHCarl10/Deb7AutoScriptVPS/master/screenfetch'
-chmod +x screenfetch
+# install neofetch
+echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
+curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
+apt-get update
+apt-get install neofetch
+
+echo "deb http://dl.bintray.com/dawidd6/neofetch jessie main" | tee -a /etc/apt/sources.list
+curl "https://bintray.com/user/downloadSubjectPublicKey?username=bintray"| apt-key add -
+apt-get update
+apt-get install neofetch
 
 # info
 clear
-echo -e ""
-echo -e "\e[94m         _|    _|  _|_|_|_|  _|    _|  _|_|      _| _|_|_|_|_|  _|_|_|_|  _|_|_|     "
-echo -e "\e[94m         _|    _|  _|    _|  _|    _|  _|  _|    _|     _|      _|        _|    _| "
-echo -e "\e[94m         _|_|_|_|  _|    _|  _|    _|  _|    _|  _|     _|      _|_|_|    _|    _| "
-echo -e "\e[94m         _|    _|  _|    _|  _|    _|  _|      _|_|     _|      _|        _|    _| "
-echo -e "\e[94m         _|    _|  _|_|_|_|  _|_|_|_|  _|        _|     _|      _|_|_|_|  _|_|_|            "
-echo -e "\e[94m.  ---------------------------------------------------------------      "
-echo -e "\e[94m##################################################"
-echo -e "\e[94m         VPSAutoScript by Hounted123         "
-echo -e "\e[94m                                                  "
-echo -e "\e[94m                    Services                      "
-echo -e "\e[94m                                                  "
-echo -e "\e[94m    OpenSSH        :   22, 143                    "
-echo -e "\e[94m    Dropbear       :   80, 443                    "
-echo -e "\e[94m    SSL            :   442                        "
-echo -e "\e[94m    Squid3         :   3128, 8000, 8080           "
-echo -e "\e[94m    OpenVPN        :   TCP 1194                   "
-echo -e "\e[94m    BadVPN         :   UDPGW 7300                 "
-echo -e "\e[94m    Nginx          :   80                         "
-echo -e "\e[94m                                                  "
-echo -e "\e[94m              Other Features Included             "
-echo -e "\e[94m                                                  "
-echo -e "\e[94m    Timezone       :   Asia/Manila (GMT +8)       "
-echo -e "\e[94m    Webmin         :   http://$MYIP:10000/        "
-echo -e "\e[94m    IPV6           :   [OFF]                      "
-echo -e "\e[94m    Cron Scheduler :   [ON]                       "
-echo -e "\e[94m    Fail2Ban       :   [ON]                       "
-echo -e "\e[94m    DDOS Deflate   :   [ON]                       "
-echo -e "\e[94m    LibXML Parser  :   {ON]                       "
-echo -e "\e[94m##################################################"
-echo -e "\e[0m                                                  "
-read -n1 -r -p "          Press Enter To Show Commands          "
-menu
+echo "Autoscript Include:" | tee log-install.txt
+echo "===========================================" | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "Service"  | tee -a log-install.txt
+echo "-------"  | tee -a log-install.txt
+echo "OpenSSH  : 22, 444"  | tee -a log-install.txt
+echo "Dropbear : 143, 3128"  | tee -a log-install.txt
+echo "SSL      : 443"  | tee -a log-install.txt
+echo "Squid3   : 8000, 8080 (limit to IP SSH)"  | tee -a log-install.txt
+echo "OpenVPN  : TCP 1194 (client config : http://$MYIP:81/client.ovpn)"  | tee -a log-install.txt
+echo "badvpn   : badvpn-udpgw port 7300"  | tee -a log-install.txt
+echo "nginx    : 81"  | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "Script"  | tee -a log-install.txt
+echo "------"  | tee -a log-install.txt
+echo "menu (Displays a list of available commands)"  | tee -a log-install.txt
+echo "usernew (Creating an SSH Account)"  | tee -a log-install.txt
+echo "trial (Create a Trial Account)"  | tee -a log-install.txt
+echo "delete (Clearing SSH Account)"  | tee -a log-install.txt
+echo "check (Check User Login)"  | tee -a log-install.txt
+echo "member (Check Member SSH)"  | tee -a log-install.txt
+echo "restart (Restart Service dropbear, webmin, squid3, openvpn and ssh)"  | tee -a log-install.txt
+echo "reboot (Reboot VPS)"  | tee -a log-install.txt
+echo "speedtest (Speedtest VPS)"  | tee -a log-install.txt
+echo "info (System Information)"  | tee -a log-install.txt
+echo "about (Information about auto install script)"  | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "Other features"  | tee -a log-install.txt
+echo "----------"  | tee -a log-install.txt
+echo "Webmin   : http://$MYIP:10000/"  | tee -a log-install.txt
+echo "Timezone : Asia/Manila (GMT +8)"  | tee -a log-install.txt
+echo "IPv6     : [off]"  | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "Original Script by Fornesia, Rzengineer & Fawzya"  | tee -a log-install.txt
+echo "Modified by Hounted"  | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "Installation Log --> /root/log-install.txt"  | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "VPS AUTO REBOOT TIME HOURS 12 NIGHT"  | tee -a log-install.txt
+echo ""  | tee -a log-install.txt
+echo "==========================================="  | tee -a log-install.txt
 cd
-rm -f /root/Deb7_AutoScript_VPS.sh
+rm -f /root/debian7.sh
